color: null
fieldLayouts:
  360a92ef-49f4-46c4-86f7-9891118b4945:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9cb3280a-d91d-41b7-bad0-4ef4607089ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69b3c42f-e31a-45f5-bd7e-874f903113f2 # Last Message
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a58db8d7-1c20-4125-8e9d-3ec109b7a941
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: faa9f15f-0a37-4b61-bf00-8359a7511f95 # Chat Users
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57c8d7c0-c369-408a-9f4d-a630ce32b724
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a81ea75-0e3b-44d4-a6bc-8315795763f1 # Messages
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 731a2a7a-61e9-4019-a743-e2bfd4975872
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6032ad0-eb90-469b-b9be-f3c1b28af52c
        userCondition: null
handle: chat
hasTitleField: false
icon: ''
name: Chat
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{chatUsers[0]["fullName"]} & {chatUsers[1]["fullName"]}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
