color: null
fieldLayouts:
  fd8d3215-82e7-45f8-a31c-587b05e0974e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6996b0b7-e66a-4fc7-89b9-aa75b25063d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac922a27-0e67-4971-bf73-92b98fdfee5a # Sender
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c78410b6-7ca5-4f95-9031-71afaa2f2a28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 887d875b-445e-4552-92a2-5beb665d46ec # Receiver
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf8de601-8f62-48df-aa55-d577281fd67f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 993457ed-fa5c-46ab-867b-29dc94c27418 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7530810-d7a6-4d68-b4f8-7c53c3d31606
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8423fa3-f646-415c-ab59-0fa58828c77a # Chat
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a585a6-095b-41b5-ac11-61ead8aac927
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b681a5f5-7319-4d10-acc2-89f55f7441c2
        userCondition: null
handle: message
hasTitleField: false
icon: ''
name: Message
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{sender[0]["fullName"]} to {receiver[0]["fullName"]}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
