color: null
fieldLayouts:
  dab9b6b2-dfcb-4194-9dcf-327026465067:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5364516b-29a5-4c43-8184-7558964f8ebc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9761bb52-245f-46e2-af43-fa313d79019d # Specialty
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4e4e95d-9a1e-4336-89df-f43d835d1fa3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9435f952-aa75-4482-9419-aa5f4de0bcb6 # Location
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48ea95ff-a213-440b-875a-214015ec64cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1408d661-772b-4329-8b77-4984146ac720 # Institution
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39e5c798-37c6-4d30-9bd1-af5f736287c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ed004ef-4a5d-431d-91d8-279bd61dcea1 # Year of Education
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5af12f6-7788-4d59-a20f-fa02604f3d99
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d417f1d-cae3-4336-87e0-8fc807e822e1 # User
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 351e2ab2-7d80-499f-9c3e-78a865b6e06e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2b9c9e1a-8545-49c7-811b-4b0b4c1e79c9
        userCondition: null
handle: profile
hasTitleField: false
icon: ''
name: profile
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{user[0]["fullName"]}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
