columnSuffix: null
handle: stripeCurrentPeriodEnd
instructions: null
name: 'Stripe Current Period End'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
