defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3eb2e7b3-810c-4f83-9411-f4b0fd08177c # Message
handle: message
maxAuthors: 1
name: Message
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0d26f912-8862-4d0f-bdf7-23ff5e08e686: # Match 
    enabledByDefault: true
    hasUrls: true
    template: message/_entry
    uriFormat: 'message/{slug}'
type: channel
